apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "marauder.fullname" . }}-config
  labels:
    {{- include "marauder.labels" . | nindent 4 }}
data:
  MARAUDER_HTTP_ADDR: ":8679"
  MARAUDER_CFSOLVER_ENABLED: "true"
  MARAUDER_CFSOLVER_URL: {{ printf "http://%s-cfsolver:9244" (include "marauder.fullname" .) | quote }}
  {{- if .Values.initialAdmin.username }}
  MARAUDER_ADMIN_INITIAL_USERNAME: {{ .Values.initialAdmin.username | quote }}
  {{- end }}
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
